name: Build
on: 
  push:
    branches: [master]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_WORKSPACE: ${{ 'Fast News.xcworkspace' }}
      XC_SCHEME: ${{ 'Fast News' }}
    steps:
    - uses: actions/checkout@v2
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - name: "Install Dependencies"
      run: "pod install"
      shell: bash
    - name: Build app
      run: /usr/bin/xcodebuild build -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
